version: '3.5'
services:
  postgres:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: ${POSTGRES_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: 'pg_isready --username=postgres && psql --username=postgres --list'
      timeout: 10s
      retries: 20

# comment out the following service if you are running the server outside of docker
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    container_name: server
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/server/src

#  uncomment the following service if you want to have access to the DB via the CLI web
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: nest-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - postgres
